name: portemonneeAN
version: '1.0-SNAPSHOT'
main: me.clin.portemonneeAN.PortemonneeAN
api-version: '1.21'
softdepend:
  - ItemsAdder
commands:
  portemonnee:
    description: Beheer en geef portemonnees.
    permission: portemonnee.command
    usage: "/<command> give [speler] | admingui"
permissions:
  portemonnee.command:
    description: Toegang tot de portemonnee testcommand.
    default: op
  portemonnee.admin:
    description: Toegang tot de admin GUI voor cash biljetten.
    default: op
